// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'da'
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Cases
	 */
	cases: string
	/**
	 * Contact
	 */
	contact: string
	/**
	 * Let's talk??
	 */
	letsTalk: string
	/**
	 * Keeping good company.
	 */
	goodCompany: string
	/**
	 * view!
	 */
	view: string
	/**
	 * menu
	 */
	menu: string
	/**
	 * back
	 */
	back: string
	/**
	 * 🤗 Hi El Danés
	 */
	mailToSubject: string
	home: {
		/**
		 * Expert in digital products web & mobile.
		 */
		header: string
		/**
		 * Want your digital product to stand out? - I can help!
		 */
		section1: string
		/**
		 * Do you need a website, webshop, app or any other digital product? Let El Danés be your digital partner who:
		 */
		section2: string
		/**
		 * Helps you make the right decisions from start to finish. Trust our experience.
		 */
		section2item1: string
		/**
		 * Handles all the technical details from development to launch.
		 */
		section2item2: string
		/**
		 * You get an exclusive solution 100 % tailored to your needs. Built with cutting edge technology where quality, speed, efficiency and automatisation are essential.
		 */
		section3: string
		/**
		 * El Danés loves “nerding” around with the latest trends & innovations. This enables us to guarantee you with an optimal solution where you get:
		 */
		section4: string
		/**
		 * Full control & flexibility.
		 */
		section4item1: string
		/**
		 * The ability to add & edit content without always needing external assistance.
		 */
		section4item2: string
		/**
		 * Being self - sustaining will promote your growth and El Danés offers the smoothest path to market for your product or idea.
		 */
		section5: string
		/**
		 * Let’s kick off your new digital journey today.El Danés is eager to hear about your idea, digital product or challenge and excited to guide you through the process.
		 */
		section6: string
		/**
		 * Reach out NOW
		 */
		callToAction: string
		/**
		 * Pleasure in the job puts perfection in the work.
		 */
		quote: string
		/**
		 * Aristoteles
		 */
		author: string
	}
	meta: {
		/**
		 * Design driven website & app development.
		 */
		title: string
		/**
		 * App & web development agency specializing in creative webs, Jamstack webs, progressive web apps, single page apps.
		 */
		description: string
	}
}

export type TranslationFunctions = {
	/**
	 * Cases
	 */
	cases: () => LocalizedString
	/**
	 * Contact
	 */
	contact: () => LocalizedString
	/**
	 * Let's talk??
	 */
	letsTalk: () => LocalizedString
	/**
	 * Keeping good company.
	 */
	goodCompany: () => LocalizedString
	/**
	 * view!
	 */
	view: () => LocalizedString
	/**
	 * menu
	 */
	menu: () => LocalizedString
	/**
	 * back
	 */
	back: () => LocalizedString
	/**
	 * 🤗 Hi El Danés
	 */
	mailToSubject: () => LocalizedString
	home: {
		/**
		 * Expert in digital products web & mobile.
		 */
		header: () => LocalizedString
		/**
		 * Want your digital product to stand out? - I can help!
		 */
		section1: () => LocalizedString
		/**
		 * Do you need a website, webshop, app or any other digital product? Let El Danés be your digital partner who:
		 */
		section2: () => LocalizedString
		/**
		 * Helps you make the right decisions from start to finish. Trust our experience.
		 */
		section2item1: () => LocalizedString
		/**
		 * Handles all the technical details from development to launch.
		 */
		section2item2: () => LocalizedString
		/**
		 * You get an exclusive solution 100 % tailored to your needs. Built with cutting edge technology where quality, speed, efficiency and automatisation are essential.
		 */
		section3: () => LocalizedString
		/**
		 * El Danés loves “nerding” around with the latest trends & innovations. This enables us to guarantee you with an optimal solution where you get:
		 */
		section4: () => LocalizedString
		/**
		 * Full control & flexibility.
		 */
		section4item1: () => LocalizedString
		/**
		 * The ability to add & edit content without always needing external assistance.
		 */
		section4item2: () => LocalizedString
		/**
		 * Being self - sustaining will promote your growth and El Danés offers the smoothest path to market for your product or idea.
		 */
		section5: () => LocalizedString
		/**
		 * Let’s kick off your new digital journey today.El Danés is eager to hear about your idea, digital product or challenge and excited to guide you through the process.
		 */
		section6: () => LocalizedString
		/**
		 * Reach out NOW
		 */
		callToAction: () => LocalizedString
		/**
		 * Pleasure in the job puts perfection in the work.
		 */
		quote: () => LocalizedString
		/**
		 * Aristoteles
		 */
		author: () => LocalizedString
	}
	meta: {
		/**
		 * Design driven website & app development.
		 */
		title: () => LocalizedString
		/**
		 * App & web development agency specializing in creative webs, Jamstack webs, progressive web apps, single page apps.
		 */
		description: () => LocalizedString
	}
}

export type Formatters = {}
