// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'da'
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * C​a​s​e​s
	 */
	cases: string
	/**
	 * C​o​n​t​a​c​t
	 */
	contact: string
	/**
	 * L​e​t​'​s​ ​t​a​l​k​?​?
	 */
	letsTalk: string
	/**
	 * K​e​e​p​i​n​g​ ​g​o​o​d​ ​c​o​m​p​a​n​y​.
	 */
	goodCompany: string
	/**
	 * v​i​e​w​!
	 */
	view: string
	/**
	 * m​e​n​u
	 */
	menu: string
	/**
	 * b​a​c​k
	 */
	back: string
	/**
	 * �​�​ ​H​i​ ​E​l​ ​D​a​n​é​s
	 */
	mailToSubject: string
	home: {
		/**
		 * E​x​p​e​r​t​ ​i​n​ ​d​i​g​i​t​a​l​ ​p​r​o​d​u​c​t​s​ ​w​e​b​ ​&​ ​m​o​b​i​l​e​.
		 */
		header: string
		/**
		 * W​a​n​t​ ​y​o​u​r​ ​d​i​g​i​t​a​l​ ​p​r​o​d​u​c​t​ ​t​o​ ​s​t​a​n​d​ ​o​u​t​?​ ​-​ ​I​ ​c​a​n​ ​h​e​l​p​!
		 */
		section1: string
		/**
		 * D​o​ ​y​o​u​ ​n​e​e​d​ ​a​ ​w​e​b​s​i​t​e​,​ ​w​e​b​s​h​o​p​,​ ​a​p​p​ ​o​r​ ​a​n​y​ ​o​t​h​e​r​ ​d​i​g​i​t​a​l​ ​p​r​o​d​u​c​t​?​ ​L​e​t​ ​E​l​ ​D​a​n​é​s​ ​b​e​ ​y​o​u​r​ ​d​i​g​i​t​a​l​ ​p​a​r​t​n​e​r​ ​w​h​o​:
		 */
		section2: string
		/**
		 * H​e​l​p​s​ ​y​o​u​ ​m​a​k​e​ ​t​h​e​ ​r​i​g​h​t​ ​d​e​c​i​s​i​o​n​s​ ​f​r​o​m​ ​s​t​a​r​t​ ​t​o​ ​f​i​n​i​s​h​.​ ​T​r​u​s​t​ ​o​u​r​ ​e​x​p​e​r​i​e​n​c​e​.
		 */
		section2item1: string
		/**
		 * H​a​n​d​l​e​s​ ​a​l​l​ ​t​h​e​ ​t​e​c​h​n​i​c​a​l​ ​d​e​t​a​i​l​s​ ​f​r​o​m​ ​d​e​v​e​l​o​p​m​e​n​t​ ​t​o​ ​l​a​u​n​c​h​.
		 */
		section2item2: string
		/**
		 * Y​o​u​ ​g​e​t​ ​a​n​ ​e​x​c​l​u​s​i​v​e​ ​s​o​l​u​t​i​o​n​ ​1​0​0​ ​%​ ​t​a​i​l​o​r​e​d​ ​t​o​ ​y​o​u​r​ ​n​e​e​d​s​.​ ​B​u​i​l​t​ ​w​i​t​h​ ​c​u​t​t​i​n​g​ ​e​d​g​e​ ​t​e​c​h​n​o​l​o​g​y​ ​w​h​e​r​e​ ​q​u​a​l​i​t​y​,​ ​s​p​e​e​d​,​ ​e​f​f​i​c​i​e​n​c​y​ ​a​n​d​ ​a​u​t​o​m​a​t​i​s​a​t​i​o​n​ ​a​r​e​ ​e​s​s​e​n​t​i​a​l​.
		 */
		section3: string
		/**
		 * E​l​ ​D​a​n​é​s​ ​l​o​v​e​s​ ​“​n​e​r​d​i​n​g​”​ ​a​r​o​u​n​d​ ​w​i​t​h​ ​t​h​e​ ​l​a​t​e​s​t​ ​t​r​e​n​d​s​ ​&​ ​i​n​n​o​v​a​t​i​o​n​s​.​ ​T​h​i​s​ ​e​n​a​b​l​e​s​ ​u​s​ ​t​o​ ​g​u​a​r​a​n​t​e​e​ ​y​o​u​ ​w​i​t​h​ ​a​n​ ​o​p​t​i​m​a​l​ ​s​o​l​u​t​i​o​n​ ​w​h​e​r​e​ ​y​o​u​ ​g​e​t​:
		 */
		section4: string
		/**
		 * F​u​l​l​ ​c​o​n​t​r​o​l​ ​&​ ​f​l​e​x​i​b​i​l​i​t​y​.
		 */
		section4item1: string
		/**
		 * T​h​e​ ​a​b​i​l​i​t​y​ ​t​o​ ​a​d​d​ ​&​ ​e​d​i​t​ ​c​o​n​t​e​n​t​ ​w​i​t​h​o​u​t​ ​a​l​w​a​y​s​ ​n​e​e​d​i​n​g​ ​e​x​t​e​r​n​a​l​ ​a​s​s​i​s​t​a​n​c​e​.
		 */
		section4item2: string
		/**
		 * B​e​i​n​g​ ​s​e​l​f​ ​-​ ​s​u​s​t​a​i​n​i​n​g​ ​w​i​l​l​ ​p​r​o​m​o​t​e​ ​y​o​u​r​ ​g​r​o​w​t​h​ ​a​n​d​ ​E​l​ ​D​a​n​é​s​ ​o​f​f​e​r​s​ ​t​h​e​ ​s​m​o​o​t​h​e​s​t​ ​p​a​t​h​ ​t​o​ ​m​a​r​k​e​t​ ​f​o​r​ ​y​o​u​r​ ​p​r​o​d​u​c​t​ ​o​r​ ​i​d​e​a​.
		 */
		section5: string
		/**
		 * L​e​t​’​s​ ​k​i​c​k​ ​o​f​f​ ​y​o​u​r​ ​n​e​w​ ​d​i​g​i​t​a​l​ ​j​o​u​r​n​e​y​ ​t​o​d​a​y​.​E​l​ ​D​a​n​é​s​ ​i​s​ ​e​a​g​e​r​ ​t​o​ ​h​e​a​r​ ​a​b​o​u​t​ ​y​o​u​r​ ​i​d​e​a​,​ ​d​i​g​i​t​a​l​ ​p​r​o​d​u​c​t​ ​o​r​ ​c​h​a​l​l​e​n​g​e​ ​a​n​d​ ​e​x​c​i​t​e​d​ ​t​o​ ​g​u​i​d​e​ ​y​o​u​ ​t​h​r​o​u​g​h​ ​t​h​e​ ​p​r​o​c​e​s​s​.
		 */
		section6: string
		/**
		 * R​e​a​c​h​ ​o​u​t​ ​N​O​W
		 */
		callToAction: string
		/**
		 * P​l​e​a​s​u​r​e​ ​i​n​ ​t​h​e​ ​j​o​b​ ​p​u​t​s​ ​p​e​r​f​e​c​t​i​o​n​ ​i​n​ ​t​h​e​ ​w​o​r​k​.
		 */
		quote: string
		/**
		 * A​r​i​s​t​o​t​e​l​e​s
		 */
		author: string
	}
	meta: {
		/**
		 * D​e​s​i​g​n​ ​d​r​i​v​e​n​ ​w​e​b​s​i​t​e​ ​&​ ​a​p​p​ ​d​e​v​e​l​o​p​m​e​n​t​.
		 */
		title: string
		/**
		 * A​p​p​ ​&​ ​w​e​b​ ​d​e​v​e​l​o​p​m​e​n​t​ ​a​g​e​n​c​y​ ​s​p​e​c​i​a​l​i​z​i​n​g​ ​i​n​ ​c​r​e​a​t​i​v​e​ ​w​e​b​s​,​ ​J​a​m​s​t​a​c​k​ ​w​e​b​s​,​ ​p​r​o​g​r​e​s​s​i​v​e​ ​w​e​b​ ​a​p​p​s​,​ ​s​i​n​g​l​e​ ​p​a​g​e​ ​a​p​p​s​.
		 */
		description: string
	}
}

export type TranslationFunctions = {
	/**
	 * Cases
	 */
	cases: () => LocalizedString
	/**
	 * Contact
	 */
	contact: () => LocalizedString
	/**
	 * Let's talk??
	 */
	letsTalk: () => LocalizedString
	/**
	 * Keeping good company.
	 */
	goodCompany: () => LocalizedString
	/**
	 * view!
	 */
	view: () => LocalizedString
	/**
	 * menu
	 */
	menu: () => LocalizedString
	/**
	 * back
	 */
	back: () => LocalizedString
	/**
	 * 🤗 Hi El Danés
	 */
	mailToSubject: () => LocalizedString
	home: {
		/**
		 * Expert in digital products web & mobile.
		 */
		header: () => LocalizedString
		/**
		 * Want your digital product to stand out? - I can help!
		 */
		section1: () => LocalizedString
		/**
		 * Do you need a website, webshop, app or any other digital product? Let El Danés be your digital partner who:
		 */
		section2: () => LocalizedString
		/**
		 * Helps you make the right decisions from start to finish. Trust our experience.
		 */
		section2item1: () => LocalizedString
		/**
		 * Handles all the technical details from development to launch.
		 */
		section2item2: () => LocalizedString
		/**
		 * You get an exclusive solution 100 % tailored to your needs. Built with cutting edge technology where quality, speed, efficiency and automatisation are essential.
		 */
		section3: () => LocalizedString
		/**
		 * El Danés loves “nerding” around with the latest trends & innovations. This enables us to guarantee you with an optimal solution where you get:
		 */
		section4: () => LocalizedString
		/**
		 * Full control & flexibility.
		 */
		section4item1: () => LocalizedString
		/**
		 * The ability to add & edit content without always needing external assistance.
		 */
		section4item2: () => LocalizedString
		/**
		 * Being self - sustaining will promote your growth and El Danés offers the smoothest path to market for your product or idea.
		 */
		section5: () => LocalizedString
		/**
		 * Let’s kick off your new digital journey today.El Danés is eager to hear about your idea, digital product or challenge and excited to guide you through the process.
		 */
		section6: () => LocalizedString
		/**
		 * Reach out NOW
		 */
		callToAction: () => LocalizedString
		/**
		 * Pleasure in the job puts perfection in the work.
		 */
		quote: () => LocalizedString
		/**
		 * Aristoteles
		 */
		author: () => LocalizedString
	}
	meta: {
		/**
		 * Design driven website & app development.
		 */
		title: () => LocalizedString
		/**
		 * App & web development agency specializing in creative webs, Jamstack webs, progressive web apps, single page apps.
		 */
		description: () => LocalizedString
	}
}

export type Formatters = {}
