// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'da'
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * C​a​s​e​s
	 */
	cases: string
	/**
	 * C​o​n​t​a​c​t
	 */
	contact: string
	/**
	 * L​e​t​'​s​ ​t​a​l​k​?​?
	 */
	letsTalk: string
	/**
	 * K​e​e​p​i​n​g​ ​g​o​o​d​ ​c​o​m​p​a​n​y​.
	 */
	goodCompany: string
	/**
	 * v​i​e​w​!
	 */
	view: string
	/**
	 * m​e​n​u
	 */
	menu: string
	/**
	 * b​a​c​k
	 */
	back: string
	/**
	 * �​�​ ​H​i​ ​E​l​ ​D​a​n​é​s
	 */
	mailToSubject: string
	home: {
		/**
		 * S​e​n​i​o​r​ ​F​r​e​e​l​a​n​c​e​ ​W​e​b​ ​D​e​v​e​l​o​p​e​r
		 */
		header: string
		/**
		 * I​ ​c​a​n​ ​a​s​s​i​s​t​ ​w​i​t​h​:
		 */
		headerTwo: string
		/**
		 * E​x​p​e​r​t​ ​i​n​ ​d​i​g​i​t​a​l​ ​p​r​o​d​u​c​t​s​ ​w​e​b​ ​&​ ​m​o​b​i​l​e​.
		 */
		footer: string
		/**
		 * W​a​n​t​ ​y​o​u​r​ ​d​i​g​i​t​a​l​ ​p​r​o​d​u​c​t​ ​t​o​ ​s​t​a​n​d​ ​o​u​t​?​ ​-​ ​I​ ​c​a​n​ ​h​e​l​p​!
		 */
		section1: string
		/**
		 * D​o​ ​y​o​u​ ​n​e​e​d​ ​a​ ​w​e​b​s​i​t​e​,​ ​w​e​b​s​h​o​p​,​ ​a​p​p​ ​o​r​ ​a​n​y​ ​o​t​h​e​r​ ​d​i​g​i​t​a​l​ ​p​r​o​d​u​c​t​?​ ​L​e​t​ ​E​l​ ​D​a​n​é​s​ ​b​e​ ​y​o​u​r​ ​d​i​g​i​t​a​l​ ​p​a​r​t​n​e​r​ ​w​h​o​:
		 */
		section2: string
		/**
		 * H​e​l​p​s​ ​y​o​u​ ​m​a​k​e​ ​t​h​e​ ​r​i​g​h​t​ ​d​e​c​i​s​i​o​n​s​ ​f​r​o​m​ ​s​t​a​r​t​ ​t​o​ ​f​i​n​i​s​h​.​ ​T​r​u​s​t​ ​o​u​r​ ​e​x​p​e​r​i​e​n​c​e​.
		 */
		section2item1: string
		/**
		 * H​a​n​d​l​e​s​ ​a​l​l​ ​t​h​e​ ​t​e​c​h​n​i​c​a​l​ ​d​e​t​a​i​l​s​ ​f​r​o​m​ ​d​e​v​e​l​o​p​m​e​n​t​ ​t​o​ ​l​a​u​n​c​h​.
		 */
		section2item2: string
		/**
		 * Y​o​u​ ​g​e​t​ ​a​n​ ​e​x​c​l​u​s​i​v​e​ ​s​o​l​u​t​i​o​n​ ​1​0​0​ ​%​ ​t​a​i​l​o​r​e​d​ ​t​o​ ​y​o​u​r​ ​n​e​e​d​s​.​ ​B​u​i​l​t​ ​w​i​t​h​ ​c​u​t​t​i​n​g​ ​e​d​g​e​ ​t​e​c​h​n​o​l​o​g​y​ ​w​h​e​r​e​ ​q​u​a​l​i​t​y​,​ ​s​p​e​e​d​,​ ​e​f​f​i​c​i​e​n​c​y​ ​a​n​d​ ​a​u​t​o​m​a​t​i​s​a​t​i​o​n​ ​a​r​e​ ​e​s​s​e​n​t​i​a​l​.
		 */
		section3: string
		/**
		 * E​l​ ​D​a​n​é​s​ ​l​o​v​e​s​ ​“​n​e​r​d​i​n​g​”​ ​a​r​o​u​n​d​ ​w​i​t​h​ ​t​h​e​ ​l​a​t​e​s​t​ ​t​r​e​n​d​s​ ​&​ ​i​n​n​o​v​a​t​i​o​n​s​.​ ​T​h​i​s​ ​e​n​a​b​l​e​s​ ​u​s​ ​t​o​ ​g​u​a​r​a​n​t​e​e​ ​y​o​u​ ​w​i​t​h​ ​a​n​ ​o​p​t​i​m​a​l​ ​s​o​l​u​t​i​o​n​ ​w​h​e​r​e​ ​y​o​u​ ​g​e​t​:
		 */
		section4: string
		/**
		 * F​u​l​l​ ​c​o​n​t​r​o​l​ ​&​ ​f​l​e​x​i​b​i​l​i​t​y​.
		 */
		section4item1: string
		/**
		 * T​h​e​ ​a​b​i​l​i​t​y​ ​t​o​ ​a​d​d​ ​&​ ​e​d​i​t​ ​c​o​n​t​e​n​t​ ​w​i​t​h​o​u​t​ ​a​l​w​a​y​s​ ​n​e​e​d​i​n​g​ ​e​x​t​e​r​n​a​l​ ​a​s​s​i​s​t​a​n​c​e​.
		 */
		section4item2: string
		/**
		 * B​e​i​n​g​ ​s​e​l​f​ ​-​ ​s​u​s​t​a​i​n​i​n​g​ ​w​i​l​l​ ​p​r​o​m​o​t​e​ ​y​o​u​r​ ​g​r​o​w​t​h​ ​a​n​d​ ​E​l​ ​D​a​n​é​s​ ​o​f​f​e​r​s​ ​t​h​e​ ​s​m​o​o​t​h​e​s​t​ ​p​a​t​h​ ​t​o​ ​m​a​r​k​e​t​ ​f​o​r​ ​y​o​u​r​ ​p​r​o​d​u​c​t​ ​o​r​ ​i​d​e​a​.
		 */
		section5: string
		/**
		 * L​e​t​’​s​ ​k​i​c​k​ ​o​f​f​ ​y​o​u​r​ ​n​e​w​ ​d​i​g​i​t​a​l​ ​j​o​u​r​n​e​y​ ​t​o​d​a​y​.​E​l​ ​D​a​n​é​s​ ​i​s​ ​e​a​g​e​r​ ​t​o​ ​h​e​a​r​ ​a​b​o​u​t​ ​y​o​u​r​ ​i​d​e​a​,​ ​d​i​g​i​t​a​l​ ​p​r​o​d​u​c​t​ ​o​r​ ​c​h​a​l​l​e​n​g​e​ ​a​n​d​ ​e​x​c​i​t​e​d​ ​t​o​ ​g​u​i​d​e​ ​y​o​u​ ​t​h​r​o​u​g​h​ ​t​h​e​ ​p​r​o​c​e​s​s​.
		 */
		section6: string
		/**
		 * R​e​a​c​h​ ​o​u​t​ ​N​O​W
		 */
		callToAction: string
		/**
		 * P​l​e​a​s​u​r​e​ ​i​n​ ​t​h​e​ ​j​o​b​ ​p​u​t​s​ ​p​e​r​f​e​c​t​i​o​n​ ​i​n​ ​t​h​e​ ​w​o​r​k​.
		 */
		quote: string
		/**
		 * A​r​i​s​t​o​t​e​l​e​s
		 */
		author: string
	}
	meta: {
		/**
		 * F​r​e​e​l​a​n​c​e​ ​W​e​b​s​i​t​e​ ​&​ ​A​p​p​ ​D​e​v​e​l​o​p​m​e​n​t​.
		 */
		title: string
		/**
		 * W​e​b​ ​a​n​d​ ​m​o​b​i​l​e​ ​d​e​v​e​l​o​p​e​r​ ​w​i​t​h​ ​o​v​e​r​ ​1​0​ ​y​e​a​r​s​ ​o​f​ ​p​r​o​f​e​s​s​i​o​n​a​l​ ​e​x​p​e​r​i​e​n​c​e​,​ ​s​p​e​c​i​a​l​i​z​i​n​g​ ​i​n​ ​a​p​p​l​i​c​a​t​i​o​n​ ​a​r​c​h​i​t​e​c​t​u​r​e​,​ ​f​r​o​n​t​-​e​n​d​ ​d​e​v​e​l​o​p​m​e​n​t​,​ ​a​n​d​ ​c​o​l​l​a​b​o​r​a​t​i​o​n​ ​w​i​t​h​i​n​ ​t​e​c​h​ ​t​e​a​m​s​.​ ​E​x​p​e​r​t​ ​i​n​ ​b​u​i​l​d​i​n​g​ ​m​o​d​e​r​n​ ​w​e​b​s​i​t​e​s​,​ ​h​y​b​r​i​d​ ​m​o​b​i​l​e​ ​a​p​p​s​,​ ​e​-​c​o​m​m​e​r​c​e​ ​p​l​a​t​f​o​r​m​s​,​ ​a​n​d​ ​a​d​d​i​n​g​ ​n​e​w​ ​f​u​n​c​t​i​o​n​a​l​i​t​i​e​s​ ​t​o​ ​e​x​i​s​t​i​n​g​ ​w​e​b​s​i​t​e​s​.​ ​E​x​t​e​n​s​i​v​e​ ​e​x​p​e​r​i​e​n​c​e​ ​i​n​ ​m​a​n​a​g​i​n​g​ ​c​l​o​u​d​ ​s​e​r​v​i​c​e​s​ ​a​n​d​ ​e​-​c​o​m​m​e​r​c​e​ ​s​o​l​u​t​i​o​n​s​ ​u​s​i​n​g​ ​C​M​S​ ​l​i​k​e​ ​C​o​n​t​e​n​t​f​u​l​,​ ​P​r​i​s​m​i​c​,​ ​a​n​d​ ​S​h​o​p​i​f​y​.​ ​F​o​c​u​s​e​d​ ​o​n​ ​p​e​r​f​o​r​m​a​n​c​e​,​ ​s​c​a​l​a​b​i​l​i​t​y​,​ ​a​n​d​ ​b​e​s​t​ ​p​r​a​c​t​i​c​e​s​,​ ​I​ ​h​a​v​e​ ​w​o​r​k​e​d​ ​o​n​ ​s​u​c​c​e​s​s​f​u​l​ ​p​r​o​j​e​c​t​s​ ​f​o​r​ ​A​d​n​a​m​i​,​ ​M​e​a​t​y​,​ ​I​b​e​r​i​a​,​ ​G​O​R​M​ ​x​ ​E​n​v​i​s​i​o​n​,​ ​a​n​d​ ​m​o​r​e​.
		 */
		description: string
	}
	roles: {
		architect: {
			/**
			 * A​r​c​h​i​t​e​c​t​ ​Y​o​u​r​ ​A​p​p
			 */
			title: string
			/**
			 * E​n​s​u​r​e​ ​y​o​u​ ​a​r​e​ ​o​f​f​ ​t​o​ ​a​ ​g​r​e​a​t​ ​s​t​a​r​t​ ​w​i​t​h​ ​a​ ​h​i​g​h​-​p​e​r​f​o​r​m​i​n​g​ ​s​o​l​u​t​i​o​n​,​ ​t​h​a​t​ ​s​c​a​l​e​s​ ​w​e​l​l​ ​a​s​ ​y​o​u​r​ ​a​p​p​l​i​c​a​t​i​o​n​ ​g​r​o​w​s​.​ ​I​ ​c​a​n​ ​a​s​s​i​s​t​ ​w​i​t​h​ ​s​e​l​e​c​t​i​n​g​ ​t​h​e​ ​t​e​c​h​ ​s​t​a​c​k​,​ ​a​p​p​l​i​c​a​t​i​o​n​ ​t​y​p​e​,​ ​a​u​t​o​m​a​t​i​o​n​ ​t​o​o​l​s​,​ ​b​e​s​t​ ​p​r​a​c​t​i​c​e​s​,​ ​a​n​d​ ​b​o​o​t​s​t​r​a​p​p​i​n​g​ ​y​o​u​r​ ​a​p​p​l​i​c​a​t​i​o​n​,​ ​a​s​ ​I​ ​h​a​v​e​ ​d​o​n​e​ ​f​o​r​ ​<​i​>​A​d​n​a​m​i​,​ ​B​r​i​t​i​s​h​ ​P​e​t​r​o​l​e​u​m​ ​&​ ​M​e​a​t​y​<​/​i​>​,​ ​a​m​o​n​g​ ​o​t​h​e​r​s​.
			 */
			subtitle: string
		}
		lead: {
			/**
			 * L​e​a​d​ ​F​r​o​n​t​-​E​n​d​ ​D​e​v​e​l​o​p​m​e​n​t
			 */
			title: string
			/**
			 * W​i​t​h​ ​o​v​e​r​ ​1​0​ ​y​e​a​r​s​ ​o​f​ ​p​r​o​f​e​s​s​i​o​n​a​l​ ​e​x​p​e​r​i​e​n​c​e​ ​i​n​ ​w​e​b​ ​a​p​p​l​i​c​a​t​i​o​n​ ​d​e​v​e​l​o​p​m​e​n​t​,​ ​I​ ​h​a​v​e​ ​l​e​d​ ​f​r​o​n​t​-​e​n​d​ ​t​e​a​m​s​,​ ​c​o​n​d​u​c​t​e​d​ ​c​o​d​e​ ​r​e​v​i​e​w​s​,​ ​e​n​s​u​r​e​d​ ​b​e​s​t​ ​p​r​a​c​t​i​c​e​s​ ​a​n​d​ ​m​e​n​t​o​r​e​d​ ​o​t​h​e​r​ ​d​e​v​e​l​o​p​e​r​s​ ​o​n​ ​p​r​o​j​e​c​t​s​ ​s​u​c​h​ ​a​s​ ​<​i​>​I​b​e​r​i​a​,​ ​A​d​n​a​m​i​ ​&​ ​F​o​r​t​K​n​o​x​s​t​e​r​.​<​/​i​>
			 */
			subtitle: string
		}
		team: {
			/**
			 * J​o​i​n​ ​Y​o​u​r​ ​T​e​c​h​ ​T​e​a​m
			 */
			title: string
			/**
			 * I​ ​a​m​ ​s​k​i​l​l​e​d​ ​a​t​ ​c​o​l​l​a​b​o​r​a​t​i​n​g​ ​w​i​t​h​ ​c​r​o​s​s​-​f​u​n​c​t​i​o​n​a​l​ ​t​e​a​m​s​ ​t​o​ ​m​e​e​t​ ​p​r​o​j​e​c​t​ ​g​o​a​l​s​ ​e​f​f​e​c​t​i​v​e​l​y​ ​a​n​d​ ​e​f​f​i​c​i​e​n​t​l​y​.​ ​L​e​t​ ​m​e​ ​h​e​l​p​ ​e​l​e​v​a​t​e​ ​y​o​u​r​ ​t​e​a​m​ ​a​n​d​ ​g​i​v​e​ ​y​o​u​ ​a​n​ ​e​d​g​e​ ​o​n​ ​t​h​e​ ​f​r​o​n​t​-​e​n​d​,​ ​a​s​ ​I​ ​h​a​v​e​ ​d​o​n​e​ ​i​n​ ​p​r​e​v​i​o​u​s​ ​r​o​l​e​s​ ​f​o​r​ ​<​i​>​A​d​n​a​m​i​,​ ​M​e​a​t​y​,​ ​N​o​w​ ​T​e​s​t​,​ ​F​o​r​t​K​n​o​x​s​t​e​r​,​ ​K​e​y​t​r​e​e​,​ ​P​a​c​k​l​i​n​k​ ​&​ ​O​p​e​n​J​a​w​ ​T​e​c​h​n​o​l​o​g​i​e​s​.​<​/​i​>
			 */
			subtitle: string
		}
		webApp: {
			/**
			 * B​u​i​l​d​ ​a​ ​M​o​d​e​r​n​ ​W​e​b​s​i​t​e
			 */
			title: string
			/**
			 * I​ ​a​m​ ​p​r​o​f​i​c​i​e​n​t​ ​i​n​ ​b​u​i​l​d​i​n​g​ ​p​i​x​e​l​-​p​e​r​f​e​c​t​ ​w​e​b​s​i​t​e​s​ ​a​c​c​o​r​d​i​n​g​ ​t​o​ ​y​o​u​r​ ​d​e​s​i​g​n​s​.​ ​I​n​t​e​g​r​a​t​i​n​g​ ​w​i​t​h​ ​a​ ​h​e​a​d​l​e​s​s​ ​C​M​S​ ​a​l​l​o​w​s​ ​y​o​u​ ​t​o​ ​a​d​d​ ​a​n​d​ ​e​d​i​t​ ​c​o​n​t​e​n​t​ ​w​i​t​h​o​u​t​ ​n​e​e​d​i​n​g​ ​e​x​t​e​r​n​a​l​ ​a​s​s​i​s​t​a​n​c​e​.​ ​I​ ​h​a​v​e​ ​e​x​t​e​n​s​i​v​e​ ​e​x​p​e​r​i​e​n​c​e​ ​w​i​t​h​ ​v​a​r​i​o​u​s​ ​C​M​S​ ​p​r​o​v​i​d​e​r​s​ ​s​u​c​h​ ​a​s​ ​<​i​>​C​o​n​t​e​n​t​f​u​l​,​ ​P​r​i​s​m​i​c​,​ ​S​t​o​r​y​b​l​o​k​<​/​i​>​,​ ​a​n​d​ ​o​t​h​e​r​s​,​ ​a​s​ ​d​e​m​o​n​s​t​r​a​t​e​d​ ​i​n​ ​c​a​s​e​s​ ​f​o​r​ ​<​i​>​V​e​r​m​o​u​t​h​.​N​u​,​ ​G​O​R​M​ ​x​ ​E​n​v​i​s​i​o​n​,​ ​F​l​i​n​t​ ​&​ ​Ø​r​s​t​e​d​,​ ​B​a​u​z​.​s​t​u​d​i​o​<​/​i​>​,​ ​a​n​d​ ​m​o​r​e​.
			 */
			subtitle: string
		}
		mobileApp: {
			/**
			 * C​r​e​a​t​e​ ​a​ ​H​y​b​r​i​d​ ​M​o​b​i​l​e​ ​A​p​p
			 */
			title: string
			/**
			 * M​y​ ​e​x​t​e​n​s​i​v​e​ ​w​e​b​ ​d​e​v​e​l​o​p​m​e​n​t​ ​e​x​p​e​r​i​e​n​c​e​,​ ​c​o​m​b​i​n​e​d​ ​w​i​t​h​ ​s​o​m​e​ ​n​a​t​i​v​e​ ​i​O​S​ ​d​e​v​e​l​o​p​m​e​n​t​,​ ​e​n​a​b​l​e​s​ ​m​e​ ​t​o​ ​b​u​i​l​d​ ​h​y​b​r​i​d​ ​m​o​b​i​l​e​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​u​s​i​n​g​ ​R​e​a​c​t​ ​N​a​t​i​v​e​.​ ​T​h​i​s​ ​a​p​p​r​o​a​c​h​ ​o​f​f​e​r​s​ ​s​i​g​n​i​f​i​c​a​n​t​ ​t​i​m​e​ ​a​n​d​ ​c​o​s​t​ ​s​a​v​i​n​g​s​,​ ​a​s​ ​s​e​e​n​ ​i​n​ ​a​p​p​s​ ​d​e​v​e​l​o​p​e​d​ ​f​o​r​ ​<​i​>​P​a​l​a​d​i​n​a​ ​M​a​r​k​e​t​i​n​g​ ​&​ ​M​y​T​y​p​e​ ​D​a​t​i​n​g​<​/​i​>​,​ ​a​m​o​n​g​ ​o​t​h​e​r​s​.
			 */
			subtitle: string
		}
		addFunctionality: {
			/**
			 * A​d​d​ ​N​e​w​ ​F​u​n​c​t​i​o​n​a​l​i​t​y​ ​t​o​ ​Y​o​u​r​ ​W​e​b​s​i​t​e
			 */
			title: string
			/**
			 * A​d​d​i​n​g​ ​m​o​d​e​r​n​ ​f​e​a​t​u​r​e​s​ ​t​o​ ​l​e​g​a​c​y​ ​w​e​b​s​i​t​e​s​ ​h​a​s​ ​n​e​v​e​r​ ​b​e​e​n​ ​e​a​s​i​e​r​.​ ​W​e​b​ ​c​o​m​p​o​n​e​n​t​s​,​ ​a​ ​n​e​w​ ​s​t​a​n​d​a​r​d​,​ ​a​l​l​o​w​s​ ​f​o​r​ ​b​u​i​l​d​i​n​g​ ​m​o​d​u​l​a​r​ ​c​o​m​p​o​n​e​n​t​s​ ​t​h​a​t​ ​c​a​n​ ​b​e​ ​s​e​a​m​l​e​s​s​l​y​ ​i​n​t​e​g​r​a​t​e​d​ ​i​n​t​o​ ​a​n​y​ ​e​x​i​s​t​i​n​g​ ​w​e​b​s​i​t​e​.​ ​I​ ​h​a​v​e​ ​b​u​i​l​t​ ​w​e​b​ ​c​o​m​p​o​n​e​n​t​s​ ​f​o​r​ ​<​i​>​G​O​R​M​ ​x​ ​E​n​v​i​s​i​o​n​<​/​i​>​.
			 */
			subtitle: string
		}
		eCommerce: {
			/**
			 * C​r​e​a​t​e​ ​Y​o​u​r​ ​E​-​C​o​m​m​e​r​c​e​ ​P​l​a​t​f​o​r​m
			 */
			title: string
			/**
			 * I​ ​b​u​i​l​d​ ​h​i​g​h​-​p​e​r​f​o​r​m​i​n​g​ ​e​-​c​o​m​m​e​r​c​e​ ​s​o​l​u​t​i​o​n​s​ ​t​h​a​t​ ​l​o​o​k​ ​g​r​e​a​t​,​ ​w​h​e​t​h​e​r​ ​w​i​t​h​ ​c​u​s​t​o​m​ ​b​a​c​k​e​n​d​s​,​ ​a​s​ ​w​i​t​h​ ​<​i​>​M​e​a​t​y​<​/​i​>​,​ ​o​r​ ​b​y​ ​u​t​i​l​i​z​i​n​g​ ​h​e​a​d​l​e​s​s​ ​<​i​>​S​h​o​p​i​f​y​<​/​i​>​,​ ​a​s​ ​d​o​n​e​ ​f​o​r​ ​<​i​>​T​o​m​a​ ​C​a​f​é​ ​&​ ​M​a​r​t​i​n​s​e​n​ ​N​o​r​d​i​c​<​/​i​>​.
			 */
			subtitle: string
		}
		problem: {
			/**
			 * S​o​l​v​e​ ​P​r​o​b​l​e​m​s​ ​w​i​t​h​ ​Y​o​u​r​ ​W​e​b​s​i​t​e
			 */
			title: string
			/**
			 * I​ ​a​m​ ​h​i​g​h​l​y​ ​p​r​o​f​i​c​i​e​n​t​ ​i​n​ ​t​r​o​u​b​l​e​s​h​o​o​t​i​n​g​ ​a​n​d​ ​p​r​o​b​l​e​m​-​s​o​l​v​i​n​g​,​ ​s​k​i​l​l​s​ ​I​ ​h​a​v​e​ ​h​o​n​e​d​ ​t​h​r​o​u​g​h​o​u​t​ ​m​y​ ​c​a​r​e​e​r​.​ ​L​e​t​’​s​ ​w​o​r​k​ ​t​o​g​e​t​h​e​r​ ​t​o​ ​f​i​n​d​ ​a​n​ ​e​f​f​e​c​t​i​v​e​ ​s​o​l​u​t​i​o​n​ ​t​o​ ​y​o​u​r​ ​t​e​c​h​n​i​c​a​l​ ​c​h​a​l​l​e​n​g​e​s​.
			 */
			subtitle: string
		}
		cloudService: {
			/**
			 * M​a​n​a​g​e​ ​C​l​o​u​d​ ​S​e​r​v​i​c​e​s
			 */
			title: string
			/**
			 * I​ ​h​a​v​e​ ​p​r​o​f​e​s​s​i​o​n​a​l​ ​e​x​p​e​r​i​e​n​c​e​ ​w​i​t​h​ ​m​o​s​t​ ​m​o​d​e​r​n​ ​c​l​o​u​d​ ​h​o​s​t​i​n​g​ ​s​e​r​v​i​c​e​s​,​ ​i​n​c​l​u​d​i​n​g​ ​<​i​>​A​z​u​r​e​,​ ​C​l​o​u​d​f​l​a​r​e​,​ ​N​e​t​l​i​f​y​,​ ​V​e​r​c​e​l​<​/​i​>​,​ ​a​n​d​ ​o​t​h​e​r​s​.​ ​U​t​i​l​i​z​i​n​g​ ​t​h​e​i​r​ ​s​e​r​v​e​r​l​e​s​s​ ​a​r​c​h​i​t​e​c​t​u​r​e​s​ ​a​n​d​ ​m​i​g​r​a​t​i​n​g​ ​b​e​t​w​e​e​n​ ​t​h​e​m​ ​h​a​s​ ​h​e​l​p​e​d​ ​m​e​ ​s​o​l​v​e​ ​c​h​a​l​l​e​n​g​e​s​ ​f​o​r​ ​m​o​s​t​ ​o​f​ ​m​y​ ​c​a​s​e​s​,​ ​i​n​c​l​u​d​i​n​g​ ​<​i​>​G​O​R​M​ ​x​ ​E​n​v​i​s​i​o​n​<​/​i​>​.
			 */
			subtitle: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Cases
	 */
	cases: () => LocalizedString
	/**
	 * Contact
	 */
	contact: () => LocalizedString
	/**
	 * Let's talk??
	 */
	letsTalk: () => LocalizedString
	/**
	 * Keeping good company.
	 */
	goodCompany: () => LocalizedString
	/**
	 * view!
	 */
	view: () => LocalizedString
	/**
	 * menu
	 */
	menu: () => LocalizedString
	/**
	 * back
	 */
	back: () => LocalizedString
	/**
	 * 🤗 Hi El Danés
	 */
	mailToSubject: () => LocalizedString
	home: {
		/**
		 * Senior Freelance Web Developer
		 */
		header: () => LocalizedString
		/**
		 * I can assist with:
		 */
		headerTwo: () => LocalizedString
		/**
		 * Expert in digital products web & mobile.
		 */
		footer: () => LocalizedString
		/**
		 * Want your digital product to stand out? - I can help!
		 */
		section1: () => LocalizedString
		/**
		 * Do you need a website, webshop, app or any other digital product? Let El Danés be your digital partner who:
		 */
		section2: () => LocalizedString
		/**
		 * Helps you make the right decisions from start to finish. Trust our experience.
		 */
		section2item1: () => LocalizedString
		/**
		 * Handles all the technical details from development to launch.
		 */
		section2item2: () => LocalizedString
		/**
		 * You get an exclusive solution 100 % tailored to your needs. Built with cutting edge technology where quality, speed, efficiency and automatisation are essential.
		 */
		section3: () => LocalizedString
		/**
		 * El Danés loves “nerding” around with the latest trends & innovations. This enables us to guarantee you with an optimal solution where you get:
		 */
		section4: () => LocalizedString
		/**
		 * Full control & flexibility.
		 */
		section4item1: () => LocalizedString
		/**
		 * The ability to add & edit content without always needing external assistance.
		 */
		section4item2: () => LocalizedString
		/**
		 * Being self - sustaining will promote your growth and El Danés offers the smoothest path to market for your product or idea.
		 */
		section5: () => LocalizedString
		/**
		 * Let’s kick off your new digital journey today.El Danés is eager to hear about your idea, digital product or challenge and excited to guide you through the process.
		 */
		section6: () => LocalizedString
		/**
		 * Reach out NOW
		 */
		callToAction: () => LocalizedString
		/**
		 * Pleasure in the job puts perfection in the work.
		 */
		quote: () => LocalizedString
		/**
		 * Aristoteles
		 */
		author: () => LocalizedString
	}
	meta: {
		/**
		 * Freelance Website & App Development.
		 */
		title: () => LocalizedString
		/**
		 * Web and mobile developer with over 10 years of professional experience, specializing in application architecture, front-end development, and collaboration within tech teams. Expert in building modern websites, hybrid mobile apps, e-commerce platforms, and adding new functionalities to existing websites. Extensive experience in managing cloud services and e-commerce solutions using CMS like Contentful, Prismic, and Shopify. Focused on performance, scalability, and best practices, I have worked on successful projects for Adnami, Meaty, Iberia, GORM x Envision, and more.
		 */
		description: () => LocalizedString
	}
	roles: {
		architect: {
			/**
			 * Architect Your App
			 */
			title: () => LocalizedString
			/**
			 * Ensure you are off to a great start with a high-performing solution, that scales well as your application grows. I can assist with selecting the tech stack, application type, automation tools, best practices, and bootstrapping your application, as I have done for <i>Adnami, British Petroleum & Meaty</i>, among others.
			 */
			subtitle: () => LocalizedString
		}
		lead: {
			/**
			 * Lead Front-End Development
			 */
			title: () => LocalizedString
			/**
			 * With over 10 years of professional experience in web application development, I have led front-end teams, conducted code reviews, ensured best practices and mentored other developers on projects such as <i>Iberia, Adnami & FortKnoxster.</i>
			 */
			subtitle: () => LocalizedString
		}
		team: {
			/**
			 * Join Your Tech Team
			 */
			title: () => LocalizedString
			/**
			 * I am skilled at collaborating with cross-functional teams to meet project goals effectively and efficiently. Let me help elevate your team and give you an edge on the front-end, as I have done in previous roles for <i>Adnami, Meaty, Now Test, FortKnoxster, Keytree, Packlink & OpenJaw Technologies.</i>
			 */
			subtitle: () => LocalizedString
		}
		webApp: {
			/**
			 * Build a Modern Website
			 */
			title: () => LocalizedString
			/**
			 * I am proficient in building pixel-perfect websites according to your designs. Integrating with a headless CMS allows you to add and edit content without needing external assistance. I have extensive experience with various CMS providers such as <i>Contentful, Prismic, Storyblok</i>, and others, as demonstrated in cases for <i>Vermouth.Nu, GORM x Envision, Flint & Ørsted, Bauz.studio</i>, and more.
			 */
			subtitle: () => LocalizedString
		}
		mobileApp: {
			/**
			 * Create a Hybrid Mobile App
			 */
			title: () => LocalizedString
			/**
			 * My extensive web development experience, combined with some native iOS development, enables me to build hybrid mobile applications using React Native. This approach offers significant time and cost savings, as seen in apps developed for <i>Paladina Marketing & MyType Dating</i>, among others.
			 */
			subtitle: () => LocalizedString
		}
		addFunctionality: {
			/**
			 * Add New Functionality to Your Website
			 */
			title: () => LocalizedString
			/**
			 * Adding modern features to legacy websites has never been easier. Web components, a new standard, allows for building modular components that can be seamlessly integrated into any existing website. I have built web components for <i>GORM x Envision</i>.
			 */
			subtitle: () => LocalizedString
		}
		eCommerce: {
			/**
			 * Create Your E-Commerce Platform
			 */
			title: () => LocalizedString
			/**
			 * I build high-performing e-commerce solutions that look great, whether with custom backends, as with <i>Meaty</i>, or by utilizing headless <i>Shopify</i>, as done for <i>Toma Café & Martinsen Nordic</i>.
			 */
			subtitle: () => LocalizedString
		}
		problem: {
			/**
			 * Solve Problems with Your Website
			 */
			title: () => LocalizedString
			/**
			 * I am highly proficient in troubleshooting and problem-solving, skills I have honed throughout my career. Let’s work together to find an effective solution to your technical challenges.
			 */
			subtitle: () => LocalizedString
		}
		cloudService: {
			/**
			 * Manage Cloud Services
			 */
			title: () => LocalizedString
			/**
			 * I have professional experience with most modern cloud hosting services, including <i>Azure, Cloudflare, Netlify, Vercel</i>, and others. Utilizing their serverless architectures and migrating between them has helped me solve challenges for most of my cases, including <i>GORM x Envision</i>.
			 */
			subtitle: () => LocalizedString
		}
	}
}

export type Formatters = {}
