import { error } from '@sveltejs/kit'

const passGoogle =
  'https://pay.google.com/gp/v/save/eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJidXNpbmVzcy1jYXJkc0BidXNpbmVzcy1jYXJkcy0zOTk2MDkuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJhdWQiOiJnb29nbGUiLCJvcmlnaW5zIjpbInd3dy5leGFtcGxlLmNvbSJdLCJ0eXAiOiJzYXZldG93YWxsZXQiLCJwYXlsb2FkIjp7ImdlbmVyaWNDbGFzc2VzIjpbeyJpZCI6IjMzODgwMDAwMDAwMjIyNjgwMjAuRWwtRGFuZXMxIn1dLCJnZW5lcmljT2JqZWN0cyI6W3siaWQiOiIzMzg4MDAwMDAwMDIyMjY4MDIwLkVsLURhbmVzIiwiY2xhc3NJZCI6IjMzODgwMDAwMDAwMjIyNjgwMjAuRWwtRGFuZXMxIiwic3RhdGUiOiJBQ1RJVkUiLCJsb2dvIjp7InNvdXJjZVVyaSI6eyJ1cmkiOiJodHRwczovL2ltYWdlZGVsaXZlcnkubmV0L3JPVGM5dEtDVFFCYzl6dGtpQlRYX3cvZGM0NGRiZTMtZmVhNC00ZGE1LTAxMWMtMTQwMDIzMDYxMTAwL3B1YmxpYyJ9fSwiY2FyZFRpdGxlIjp7ImRlZmF1bHRWYWx1ZSI6eyJsYW5ndWFnZSI6ImVuLVVTIiwidmFsdWUiOiJFbCBEYW7DqXMgU29sdXRpb25zIn19LCJoZWFkZXIiOnsiZGVmYXVsdFZhbHVlIjp7Imxhbmd1YWdlIjoiZW4tVVMiLCJ2YWx1ZSI6IkNocmlzdGlhbiBad2VyZ2l1cyJ9fSwidGV4dE1vZHVsZXNEYXRhIjpbeyJpZCI6InRlbDoiLCJoZWFkZXIiOiJUZWw6IiwiYm9keSI6IiszNCA2MjIgNzYzIDcwMyJ9LHsiaWQiOiJtYWlsOiIsImhlYWRlciI6Ik1haWw6IiwiYm9keSI6ImNocmlzdGlhbkBlbGRhbmVzLmNvbSJ9LHsiaWQiOiJjaWYiLCJoZWFkZXIiOiJDSUY6IiwiYm9keSI6IkI0NDY2NDQyMyJ9LHsiaWQiOiJhZGRyZXNzIiwiaGVhZGVyIjoiQWRkcmVzcyIsImJvZHkiOiJDYWxsZSBFbWJhamFkb3JlcyAzMiA3QiAgXG4yODAxMiBNYWRyaWQifV0sImJhcmNvZGUiOnsidHlwZSI6IlFSX0NPREUiLCJ2YWx1ZSI6Imh0dHBzOi8vd3d3LmVsZGFuw6lzLmNvbS9jb250YWN0L2NocmlzdGlhbiIsImFsdGVybmF0ZVRleHQiOiJTaGFyZSJ9LCJoZXhCYWNrZ3JvdW5kQ29sb3IiOiIjMDAwMDAwIiwiaGVyb0ltYWdlIjp7InNvdXJjZVVyaSI6eyJ1cmkiOiJodHRwczovL2ltYWdlZGVsaXZlcnkubmV0L3JPVGM5dEtDVFFCYzl6dGtpQlRYX3cvNjE2MDhiMDktNjdhMy00MzdiLTRiMDItNDg4YWNiZDhhZDAwL3B1YmxpYyJ9LCJjb250ZW50RGVzY3JpcHRpb24iOnsiZGVmYXVsdFZhbHVlIjp7Imxhbmd1YWdlIjoiZW4tVVMiLCJ2YWx1ZSI6IkhFUk9fSU1BR0VfREVTQ1JJUFRJT04ifX19fV19LCJpYXQiOjE2OTY1ODQ5MjV9.iY8LFwWbs6-ixcy3Ql-42poOxMj3YFTCmQX81vkTIDwBZBCV-_2vamix7Jc7sUDdO8Um2z7_viHn-cNbKULoypoDPRHhT7_gASDgxWifskILBi4BCjbr3cKF0PY-iWahsdaGEdxRJMwNgntv97wrKxWEUbkMTI9CUph15tfkDialU3pcdp_myKUJ4hvbqIHXDMtb68y05R5Wj-GdhJYLkTTAokIq1nZLn6ht7tXFfyGp0cHyDwto0DPvhQt1-FYLJcSQjh7Jw6GJvou2Dujml4gdUTcL1x2Mp-G9brA-vtmqcDqxLt2BMs0qTgrH18huM3MUfvxy4_4umzuY70Xl4A'
/** @type {import('./$types').PageLoad} */
export function load({ url }) {
  const pkpass = `${url.origin}/el-danes.pkpass`
  if (!passGoogle || !pkpass) {
    throw error(404)
  }
  return {
    passGoogle,
    pkpass,
  }
}
